import { TBookProps } from "./../../index";

export const BookData: TBookProps[] = [
  {
    id: 1,
    book: "Point Blank (À bout portant)",
    author: "Maurice Coombe",
    pages: 619,
  },
  {
    id: 2,
    book: "How to Cook Your Life",
    author: "Maryanna Bellingham",
    pages: 553,
  },
  {
    id: 3,
    book: "Passenger Side",
    author: "Kaja Darlington",
    pages: 239,
  },
  {
    id: 4,
    book: "Final Option, The (Who Dares Wins)",
    author: "Tabbi Brendel",
    pages: 993,
  },
  {
    id: 5,
    book: "Falling Awake",
    author: "Dulcine MacFadyen",
    pages: 661,
  },
  {
    id: 6,
    book: "Sweet November",
    author: "Forest Beckhouse",
    pages: 755,
  },
  {
    id: 7,
    book: "Future, The",
    author: "Mady Woodford",
    pages: 854,
  },
  {
    id: 8,
    book: "Notes on a Scandal",
    author: "Deana Guidoni",
    pages: 200,
  },
  {
    id: 9,
    book: "First Daughter",
    author: "Leonid Callcott",
    pages: 910,
  },
  {
    id: 10,
    book: "Greatest Show on Earth, The",
    author: "Laney Poleye",
    pages: 996,
  },
  {
    id: 11,
    book: "Burning Plain, The",
    author: "Garrik Hawksby",
    pages: 918,
  },
  {
    id: 12,
    book: "The Land Before Time IV: Journey Through the Mists",
    author: "Malva Pletts",
    pages: 599,
  },
  {
    id: 13,
    book: "Thursday",
    author: "Davidde Lotze",
    pages: 855,
  },
  {
    id: 14,
    book: "Hamiltons, The",
    author: "Silvanus Kyte",
    pages: 223,
  },
  {
    id: 15,
    book: "Ides of March, The",
    author: "Laural Duddin",
    pages: 445,
  },
  {
    id: 16,
    book: "In the Army Now",
    author: "Bendite Prestige",
    pages: 185,
  },
  {
    id: 17,
    book: "5,000 Fingers of Dr. T, The",
    author: "Pippa Jantot",
    pages: 381,
  },
  {
    id: 18,
    book: "Harvey",
    author: "Devin Secrett",
    pages: 537,
  },
  {
    id: 19,
    book: "Donkey Hide (Oslinaya shkura)",
    author: "Cinda Finby",
    pages: 575,
  },
  {
    id: 20,
    book: "Player, The",
    author: "Dorri Deighan",
    pages: 479,
  },
  {
    id: 21,
    book: "Don Quixote (Don Quijote de Orson Welles)",
    author: "Rodolphe Caudray",
    pages: 778,
  },
  {
    id: 22,
    book: "Teddy Bear (Mis)",
    author: "Janelle Fish",
    pages: 776,
  },
  {
    id: 23,
    book: "Zombies of the Stratosphere",
    author: "Theresita Teall",
    pages: 967,
  },
  {
    id: 24,
    book: "Romantic Englishwoman, The",
    author: "Rafe Onion",
    pages: 517,
  },
  {
    id: 25,
    book: "En på miljonen",
    author: "Ancell Roma",
    pages: 419,
  },
  {
    id: 26,
    book: "Just Sex and Nothing Else (Csak szex és más semmi)",
    author: "Vicki Bartolomieu",
    pages: 567,
  },
  {
    id: 27,
    book: "Wishing Stairs (Yeogo goedam 3: Yeowoo gyedan)",
    author: "Pyotr Weth",
    pages: 533,
  },
  {
    id: 28,
    book: "Fear of Flying",
    author: "Martie Gurry",
    pages: 328,
  },
  {
    id: 29,
    book: "It's Kind of a Funny Story",
    author: "Wayland Ridwood",
    pages: 374,
  },
  {
    id: 30,
    book: "American Addict",
    author: "Karolina Elphee",
    pages: 911,
  },
  {
    id: 31,
    book: "Flowers of Shanghai (Hai shang hua)",
    author: "Craggie Peidro",
    pages: 914,
  },
  {
    id: 32,
    book: "Return of the Living Dead: Necropolis",
    author: "Doro Yeates",
    pages: 894,
  },
  {
    id: 33,
    book: "Jar City (Mýrin)",
    author: "Reidar Spore",
    pages: 771,
  },
  {
    id: 34,
    book: "Ghoulies III: Ghoulies Go to College",
    author: "Ettie Attwood",
    pages: 248,
  },
  {
    id: 35,
    book: "Betrayed, The",
    author: "Ange de la Valette Parisot",
    pages: 605,
  },
  {
    id: 36,
    book: "Scott Joplin",
    author: "Kakalina McFetridge",
    pages: 264,
  },
  {
    id: 37,
    book: "Haunted, The",
    author: "Skelly Damiral",
    pages: 175,
  },
  {
    id: 38,
    book: "Simple Plan, A",
    author: "Bertina O'Cannavan",
    pages: 134,
  },
  {
    id: 39,
    book: "Loaded Weapon 1 (National Lampoon's Loaded Weapon 1)",
    author: "Jesse Cargen",
    pages: 401,
  },
  {
    id: 40,
    book: "Sicilian Clan, The (Clan des Siciliens, Le)",
    author: "Norene Bilborough",
    pages: 192,
  },
  {
    id: 41,
    book: "The Castle of Fu Manchu",
    author: "Wileen Crennell",
    pages: 458,
  },
  {
    id: 42,
    book: "Nights of Cabiria (Notti di Cabiria, Le)",
    author: "Arv Lindback",
    pages: 955,
  },
  {
    id: 43,
    book: "Lisbela e o Prisioneiro (Lisbela and the Prisoner)",
    author: "Benny Pemberton",
    pages: 246,
  },
  {
    id: 44,
    book: "Executioners from Shaolin",
    author: "Geraldine Lambal",
    pages: 331,
  },
  {
    id: 45,
    book: "Friends, The (Les Amis)",
    author: "Marylou Brosini",
    pages: 162,
  },
  {
    id: 46,
    book: "Hoop Dreams",
    author: "Barbabra Chevis",
    pages: 491,
  },
  {
    id: 47,
    book: "Rapid Fire",
    author: "Dexter Beccles",
    pages: 484,
  },
  {
    id: 48,
    book: "Blast",
    author: "Garfield Vawton",
    pages: 212,
  },
  {
    id: 49,
    book: "Death Wish",
    author: "Yancy Fittes",
    pages: 837,
  },
  {
    id: 50,
    book: "Judex",
    author: "Tades Polland",
    pages: 1000,
  },
  {
    id: 51,
    book: "Griff the Invisible",
    author: "Costanza Flaunders",
    pages: 196,
  },
  {
    id: 52,
    book: "Street Fighter",
    author: "Leopold Grice",
    pages: 719,
  },
  {
    id: 53,
    book: "Mad Dogs & Englishmen",
    author: "Norman Loughlin",
    pages: 545,
  },
  {
    id: 54,
    book: "Hell to Eternity",
    author: "Rubetta Bowkett",
    pages: 798,
  },
  {
    id: 55,
    book: "Beauty of the Day (Belle de jour)",
    author: "Addison Willcox",
    pages: 821,
  },
  {
    id: 56,
    book: "You're Next",
    author: "Martita Ruslinge",
    pages: 387,
  },
  {
    id: 57,
    book: "Spooky House",
    author: "Tami Tyndall",
    pages: 382,
  },
  {
    id: 58,
    book: "Scanners III: The Takeover (Scanner Force)",
    author: "Wilt Hallsworth",
    pages: 273,
  },
  {
    id: 59,
    book: "Merry War, A",
    author: "Avram Brazur",
    pages: 233,
  },
  {
    id: 60,
    book: "Stella",
    author: "Adrianne Ruggieri",
    pages: 753,
  },
  {
    id: 61,
    book: "Crystal Fairy & the Magical Cactus and 2012",
    author: "Berni Laister",
    pages: 340,
  },
  {
    id: 62,
    book: "Thorn Birds, The",
    author: "Bertie Stollberger",
    pages: 838,
  },
  {
    id: 63,
    book: "Circumstance",
    author: "Roderich Vaugham",
    pages: 503,
  },
  {
    id: 64,
    book: "Color of Money, The",
    author: "Ingemar Corke",
    pages: 799,
  },
  {
    id: 65,
    book: "Queen of Hearts",
    author: "Alexandros Chaff",
    pages: 217,
  },
  {
    id: 66,
    book: "Closet, The (Placard, Le)",
    author: "Fernandina Ruse",
    pages: 319,
  },
  {
    id: 67,
    book: "Dolls and Angels",
    author: "Ginnie Longstaff",
    pages: 768,
  },
  {
    id: 68,
    book: "Filmistaan",
    author: "Vikki Balm",
    pages: 598,
  },
  {
    id: 69,
    book: "G.I. Joe: The Revenge of Cobra",
    author: "Shurwood Tellenbach",
    pages: 713,
  },
  {
    id: 70,
    book: "Yearling, The",
    author: "Etan Deathridge",
    pages: 961,
  },
  {
    id: 71,
    book: "Phantom of the Megaplex",
    author: "Wylma Muzzall",
    pages: 530,
  },
  {
    id: 72,
    book: "Temp, The",
    author: "Sophey Trask",
    pages: 434,
  },
  {
    id: 73,
    book: "Married Couple, A",
    author: "Sammie Ridley",
    pages: 548,
  },
  {
    id: 74,
    book: "The War",
    author: "Chicky Noonan",
    pages: 197,
  },
  {
    id: 75,
    book: "Snake Eyes",
    author: "Evangelin Dubock",
    pages: 257,
  },
  {
    id: 76,
    book: "Dolce Vita, La",
    author: "Gerta Catling",
    pages: 535,
  },
  {
    id: 77,
    book: "In the Army Now",
    author: "Hakim Moger",
    pages: 963,
  },
  {
    id: 78,
    book: "Heavenly Body, The",
    author: "Casandra Roycroft",
    pages: 443,
  },
  {
    id: 79,
    book: "Comfort and Joy",
    author: "Mack Oxtaby",
    pages: 445,
  },
  {
    id: 80,
    book: "Rat Race, The (Garson Kanin's The Rat Race)",
    author: "Thia Marcu",
    pages: 907,
  },
  {
    id: 81,
    book: "Hollywood Knights, The",
    author: "Latia Hudspeth",
    pages: 606,
  },
  {
    id: 82,
    book: "貞子3D",
    author: "Brett Klyner",
    pages: 149,
  },
  {
    id: 83,
    book: "Every Girl Should Be Married",
    author: "Rowena Stairmand",
    pages: 813,
  },
  {
    id: 84,
    book: "Striptease",
    author: "Tracey Melburg",
    pages: 911,
  },
  {
    id: 85,
    book: "Valley Of Flowers",
    author: "Siouxie Harrigan",
    pages: 638,
  },
  {
    id: 86,
    book: "Soldier's Sweetheart, A",
    author: "Vivien Doby",
    pages: 266,
  },
  {
    id: 87,
    book: "Nicholas and Alexandra",
    author: "Briana Tatlock",
    pages: 352,
  },
  {
    id: 88,
    book: "Shadow Conspiracy",
    author: "Bo M'cowis",
    pages: 177,
  },
  {
    id: 89,
    book: "American President, The",
    author: "Ethyl Ortler",
    pages: 123,
  },
  {
    id: 90,
    book: "Zombie High",
    author: "Celia Betje",
    pages: 812,
  },
  {
    id: 91,
    book: "Cold Souls",
    author: "Aguistin Ellcome",
    pages: 131,
  },
  {
    id: 92,
    book: "Yuva",
    author: "Darcy Morot",
    pages: 147,
  },
  {
    id: 93,
    book: "Hans Christian Andersen",
    author: "Georgine Marney",
    pages: 927,
  },
  {
    id: 94,
    book: "Persepolis",
    author: "Roselia Priddie",
    pages: 886,
  },
  {
    id: 95,
    book: "Smart Money",
    author: "Barbara Devitt",
    pages: 879,
  },
  {
    id: 96,
    book: "Tideland",
    author: "Keriann Matushenko",
    pages: 703,
  },
  {
    id: 97,
    book: "Nocturno 29",
    author: "Idette Lissandrini",
    pages: 449,
  },
  {
    id: 98,
    book: "Vanishing, The",
    author: "Dinny Le Noire",
    pages: 204,
  },
  {
    id: 99,
    book: "Ashes, The (Popioly)",
    author: "Kelsi Surgey",
    pages: 801,
  },
  {
    id: 100,
    book: "Storage 24",
    author: "Malchy Brockhouse",
    pages: 260,
  },
];
