import { TMedProps } from "./../../index";

export const DrugData: TMedProps[] = [
  {
    id: 1,
    drug_name: "Galantamine Hydrobromide",
    qty: 36,
    price: 37,
    manufacturer: "Bayer",
  },
  {
    id: 2,
    drug_name: "Kleenex Instant Hand Sanitizer",
    qty: 100,
    price: 19,
  },
  {
    id: 3,
    drug_name: "SUPER ORIGIN CUSHION COMPLETE CONTROL",
    qty: 26,
    price: 41,
  },
  {
    id: 4,
    drug_name: "Dilaudid",
    qty: 67,
    price: 46,
  },
  {
    id: 5,
    drug_name: "Quinapril",
    qty: 42,
    price: 27,
  },
  {
    id: 6,
    drug_name: "PURE RED GINSENG CLEANSING",
    qty: 74,
    price: 57,
  },
  {
    id: 7,
    drug_name: "FludeoxyglucoseF18",
    qty: 39,
    price: 39,
  },
  {
    id: 8,
    drug_name: "Heparin Sodium",
    qty: 53,
    price: 14,
  },
  {
    id: 9,
    drug_name: "SPEEDGEL RX",
    qty: 50,
    price: 46,
  },
  {
    id: 10,
    drug_name: "Certus BZK Antiseptic Towelette",
    qty: 98,
    price: 14,
  },
  {
    id: 11,
    drug_name: "Isosorbide Dinitrate",
    qty: 69,
    price: 35,
  },
  {
    id: 12,
    drug_name: "Scape SPF 50 Moisturizing Face",
    qty: 58,
    price: 14,
  },
  {
    id: 13,
    drug_name: "equaline flu and sore throat",
    qty: 84,
    price: 2,
  },
  {
    id: 14,
    drug_name: "COMETRIQ",
    qty: 14,
    price: 9,
  },
  {
    id: 15,
    drug_name: "Anti Acne Exfoliating Cleansing Pads",
    qty: 98,
    price: 89,
  },
  {
    id: 16,
    drug_name: "Prialt",
    qty: 60,
    price: 54,
  },
  {
    id: 17,
    drug_name: "Adempas",
    qty: 44,
    price: 12,
  },
  {
    id: 18,
    drug_name: "FLURBIPROFEN",
    qty: 40,
    price: 52,
  },
  {
    id: 19,
    drug_name: "Bio Vine",
    qty: 75,
    price: 80,
  },
  {
    id: 20,
    drug_name: "Ciprofloxacin",
    qty: 34,
    price: 70,
  },
  {
    id: 21,
    drug_name: "Zoloft",
    qty: 22,
    price: 28,
  },
  {
    id: 22,
    drug_name: "Neti Mist Sinus Spray",
    qty: 58,
    price: 9,
  },
  {
    id: 23,
    drug_name: "Magnesium Chloride",
    qty: 77,
    price: 87,
  },
  {
    id: 24,
    drug_name: "Pacific Anti-bacterial Hand Cleanse Strawberry Essence",
    qty: 87,
    price: 59,
  },
  {
    id: 25,
    drug_name: "Health Smart Creamy Petroleum",
    qty: 61,
    price: 31,
  },
  {
    id: 26,
    drug_name: "Anti-Itch",
    qty: 13,
    price: 81,
  },
  {
    id: 27,
    drug_name: "ABIES CANADENSIS",
    qty: 57,
    price: 95,
  },
  {
    id: 28,
    drug_name: "BareMinerals",
    qty: 98,
    price: 14,
  },
  {
    id: 29,
    drug_name: "Pioglitazone",
    qty: 55,
    price: 10,
  },
  {
    id: 30,
    drug_name: "Bite Beauty",
    qty: 4,
    price: 26,
  },
  {
    id: 31,
    drug_name: "SnowSkin Face Sunscreen",
    qty: 96,
    price: 75,
  },
  {
    id: 32,
    drug_name: "simvastatin",
    qty: 7,
    price: 16,
  },
  {
    id: 33,
    drug_name: "Tormentilla Cochlearia",
    qty: 56,
    price: 73,
  },
  {
    id: 34,
    drug_name: "Glyburide",
    qty: 50,
    price: 43,
  },
  {
    id: 35,
    drug_name: "Pollens - Trees, Boxelder/Maple Mix",
    qty: 86,
    price: 39,
  },
  {
    id: 36,
    drug_name: "Carbamazepine",
    qty: 17,
    price: 50,
  },
  {
    id: 37,
    drug_name: "Sertraline Hydrochloride",
    qty: 55,
    price: 8,
  },
  {
    id: 38,
    drug_name: "Venlafaxine",
    qty: 85,
    price: 8,
  },
  {
    id: 39,
    drug_name: "Libido",
    qty: 6,
    price: 2,
  },
  {
    id: 40,
    drug_name: "Condylox",
    qty: 16,
    price: 44,
  },
  {
    id: 41,
    drug_name: "SILVADENE",
    qty: 8,
    price: 64,
  },
  {
    id: 42,
    drug_name: "Carbo Vegetabilis Kit Refill",
    qty: 70,
    price: 30,
  },
  {
    id: 43,
    drug_name: "Metronidazole",
    qty: 55,
    price: 30,
  },
  {
    id: 44,
    drug_name: "DISALCID",
    qty: 43,
    price: 86,
  },
  {
    id: 45,
    drug_name: "Anticavity Fluoride Rinse",
    qty: 57,
    price: 14,
  },
  {
    id: 46,
    drug_name: "BIRDS GARDEN LIP BALM",
    qty: 81,
    price: 26,
  },
  {
    id: 47,
    drug_name: "LOreal Paris Visible lift Serum Absolute Advanced Age Reversing Makeup Broad Spectrum SPF 17",
    qty: 23,
    price: 86,
  },
  {
    id: 48,
    drug_name: "isosorbide mononitrate",
    qty: 94,
    price: 66,
  },
  {
    id: 49,
    drug_name: "Tropicamide",
    qty: 70,
    price: 41,
  },
  {
    id: 50,
    drug_name: "Lice Treatment",
    qty: 60,
    price: 39,
  },
  {
    id: 51,
    drug_name: "Clearasil",
    qty: 89,
    price: 56,
  },
  {
    id: 52,
    drug_name: "Fludeoxyglucose F18",
    qty: 26,
    price: 6,
  },
  {
    id: 53,
    drug_name: "Thalomid",
    qty: 30,
    price: 15,
  },
  {
    id: 54,
    drug_name: "Brewers Yeast",
    qty: 65,
    price: 44,
  },
  {
    id: 55,
    drug_name: "Levisticum comp. Special Order",
    qty: 32,
    price: 80,
  },
  {
    id: 56,
    drug_name: "LANEIGE LIP TREATMENT",
    qty: 35,
    price: 43,
  },
  {
    id: 57,
    drug_name: "Lisinopril",
    qty: 58,
    price: 1,
  },
  {
    id: 58,
    drug_name: "LBEL HYDRATESS",
    qty: 21,
    price: 35,
  },
  {
    id: 59,
    drug_name: "Good Sense Severe NightTime Cold and Flu",
    qty: 90,
    price: 26,
  },
  {
    id: 60,
    drug_name: "sweet love hand sanitizer",
    qty: 98,
    price: 33,
  },
  {
    id: 61,
    drug_name: "Carisoprodol",
    qty: 91,
    price: 89,
  },
  {
    id: 62,
    drug_name: "Lansoprazole",
    qty: 53,
    price: 16,
  },
  {
    id: 63,
    drug_name: "Ketorolac Tromethamine",
    qty: 69,
    price: 5,
  },
  {
    id: 64,
    drug_name: "Equaline loperamide hydrochloride",
    qty: 6,
    price: 7,
  },
  {
    id: 65,
    drug_name: "Ropinirole Hydrochloride",
    qty: 50,
    price: 70,
  },
  {
    id: 66,
    drug_name: "Head and Shoulders Conditioner",
    qty: 90,
    price: 73,
  },
  {
    id: 67,
    drug_name: "Modafinil",
    qty: 72,
    price: 39,
  },
  {
    id: 68,
    drug_name: "CORFEN",
    qty: 53,
    price: 79,
  },
  {
    id: 69,
    drug_name: "Quetiapine fumarate",
    qty: 14,
    price: 52,
  },
  {
    id: 70,
    drug_name: "Tretinoin",
    qty: 54,
    price: 79,
  },
  {
    id: 71,
    drug_name: "XtraCare Anti-Dandruff Hair Cleanse",
    qty: 63,
    price: 9,
  },
  {
    id: 72,
    drug_name: "CRAB",
    qty: 80,
    price: 4,
  },
  {
    id: 73,
    drug_name: "Acacia",
    qty: 55,
    price: 29,
  },
  {
    id: 74,
    drug_name: "Maxipime",
    qty: 98,
    price: 83,
  },
  {
    id: 75,
    drug_name: "Mag-Al Plus XS",
    qty: 53,
    price: 18,
  },
  {
    id: 76,
    drug_name: "Theophylline",
    qty: 49,
    price: 26,
  },
  {
    id: 77,
    drug_name: "Ketorolac Tromethamine",
    qty: 75,
    price: 57,
  },
  {
    id: 78,
    drug_name: "Oxygen",
    qty: 23,
    price: 92,
  },
  {
    id: 79,
    drug_name: "Visudyne",
    qty: 98,
    price: 40,
  },
  {
    id: 80,
    drug_name: "Viscum 3",
    qty: 36,
    price: 49,
  },
  {
    id: 81,
    drug_name: "Echinacea Thuja Special Order",
    qty: 44,
    price: 33,
  },
  {
    id: 82,
    drug_name: "Ropinirole Hydrochloride",
    qty: 48,
    price: 16,
  },
  {
    id: 83,
    drug_name: "Diltiazem Hydrochloride",
    qty: 27,
    price: 41,
  },
  {
    id: 84,
    drug_name: "care one ibuprofen cold and sinus",
    qty: 72,
    price: 55,
  },
  {
    id: 85,
    drug_name: "SHISEIDO SUN PROTECTION EYE",
    qty: 4,
    price: 80,
  },
  {
    id: 86,
    drug_name: "White Tea Antibacterial",
    qty: 36,
    price: 14,
  },
  {
    id: 87,
    drug_name: "Wintergreen Isopropyl Alcohol",
    qty: 94,
    price: 38,
  },
  {
    id: 88,
    drug_name: "CENTER-AL - PLANTAGO LANCEOLATA POLLEN",
    qty: 21,
    price: 29,
  },
  {
    id: 89,
    drug_name: "Zolpidem Tartrate",
    qty: 85,
    price: 14,
  },
  {
    id: 90,
    drug_name: "EMLA",
    qty: 46,
    price: 63,
  },
  {
    id: 91,
    drug_name: "Up and Up Naproxen Sodium",
    qty: 70,
    price: 92,
  },
  {
    id: 92,
    drug_name: "Salex",
    qty: 81,
    price: 58,
  },
  {
    id: 93,
    drug_name: "Diethylpropion Hydrochloride",
    qty: 65,
    price: 52,
  },
  {
    id: 94,
    drug_name: "Glucotrol",
    qty: 19,
    price: 17,
  },
  {
    id: 95,
    drug_name: "Fexofenadine Hydrochloride",
    qty: 41,
    price: 22,
  },
  {
    id: 96,
    drug_name: "Naproxen Sodium",
    qty: 94,
    price: 88,
  },
  {
    id: 97,
    drug_name: "IBUPROFEN",
    qty: 6,
    price: 61,
  },
  {
    id: 98,
    drug_name: "Oxygen",
    qty: 69,
    price: 51,
  },
  {
    id: 99,
    drug_name: "omeprazole",
    qty: 7,
    price: 89,
  },
  {
    id: 100,
    drug_name: "Esterified Estrogens and Methyltestosterone",
    qty: 24,
    price: 57,
  },
];
